export const PROJECTS = [
  {
    num: "01",
    title: "RFID-Based CPSC Student Monitoring System with Automated Photo Capture and Email Notification",
    category: "Python Django",
    desc: "RFID-based student monitoring system with automated photo capture, email notifications, Google Drive export, and administrative reporting.",
    tech: ["Python Django", "MySQL"],
    awards: ["Best Capstone Paper", "Best Capstone System"],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/RFID-Student-Monitoring-System",
    linkText: "View Project →",
  },
  {
    num: "02",
    title: "ResQR - Disaster Relief Management System",
    category: "CodeIgniter 4",
    desc: "QR code-based disaster relief management system for registering beneficiaries, monitoring relief distribution, and coordinating emergency response operations.",
    tech: ["HTML", "CSS", "PHP", "MySQL", "CodeIgniter 4"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/ResQR-Disaster-Relief-Management-System",
    linkText: "View Project →",
  },
  {
    num: "03",
    title: "iTrak - Terminal Management System",
    category: "CodeIgniter 4",
    desc: "RFID-based terminal management system for monitoring driver attendance, managing routes and queues, processing payments, and providing real-time operational analytics.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/iTrak-Terminal-Management-System",
    linkText: "View Project →",
  },
  {
    num: "04",
    title: "DocuTrack - Document Tracking System",
    category: "CodeIgniter 4",
    desc: "Document tracking system for organizing, archiving, tagging, and approving official letters, with Google Drive integration for centralized storage and synchronization.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Document-Tracking-System-DocuTrack",
    linkText: "View Project →",
  },
  {
    num: "05",
    title: "Boarding House Rental System",
    category: "CodeIgniter 4",
    desc: "Web-based boarding house rental platform for managing property listings, bookings, payments, and reviews with separate access for students, landlords, and administrators.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/BH-Rental-System",
    linkText: "View Project →",
  },
  {
    num: "06",
    title: "PayTrack - Employee Payroll Management System",
    category: "CodeIgniter 4",
    desc: "PHP-based payroll management system for handling employee compensation, deductions, and payroll processing with centralized record management.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/PayTrack-Employee-Payroll-Management-System",
    linkText: "View Project →",
  },
  {
    num: "07",
    title: "Barangay Residents Management System",
    category: "CodeIgniter 4",
    desc: "Web-based system for Barangay Benoni, Mahinog, Camiguin, designed to streamline resident records, reservations, payments, and reporting.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Barangay-Residents-Management-System",
    linkText: "View Project →",
  },
  {
    num: "08",
    title: "Sari-Sari Store Utang Management System",
    category: "CodeIgniter 4",
    desc: "Web-based system for managing customer credit accounts, tracking outstanding debts, recording payments, and handling item reservations for a sari-sari store.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Sari-Sari-Store-Utang-Management-System",
    linkText: "View Project →",
  },
  {
    num: "09",
    title: "Employee Management System",
    category: "CodeIgniter 4",
    desc: "Web-based system for managing employee records, attendance tracking, payroll processing, and employee requests in one platform.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Employee-Management-System",
    linkText: "View Project →",
  },
  {
    num: "10",
    title: "Motorstar Mambajao Management System",
    category: "CodeIgniter 4",
    desc: "Web-based motorcycle rental management system featuring bike browsing, reservation management, rental tracking, payment processing, and report generation.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/Motorstar-Mambajao-Management-System",
    linkText: "View Project →",
  },
  {
    num: "11",
    title: "CPSC Library System",
    category: "CodeIgniter 4",
    desc: "Web-based Library Management System for managing books, members, borrowing transactions, and fines with streamlined catalog and circulation workflows.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/CPSC-Library-System",
    linkText: "View Project →",
  },
  {
    num: "12",
    title: "Payroll Management System",
    category: "CodeIgniter 4",
    desc: "Web-based employee management system for attendance tracking, payroll processing, and employee request management with centralized HR workflows.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Payroll-Management-System",
    linkText: "View Project →",
  },
  {
    num: "13",
    title: "Barangay Data Management System",
    category: "CodeIgniter 4",
    desc: "Web-based system for managing barangay resident records and official reports with simplified data entry, tracking, and document generation.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Barangay-Data-Management-System",
    linkText: "View Project →",
  },
  {
    num: "14",
    title: "IAS Client Satisfaction Evaluation and Management System",
    category: "Python Flask",
    desc: "Web-based customer satisfaction survey management system for creating, distributing, and analyzing client feedback with ease.",
    tech: ["Python Flask", "MySQL", "HTML", "CSS"],
    awards: [],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/IAS-Client-Satisfaction-Evaluation-and-Management-System",
    linkText: "View Project →",
  },
  {
    num: "15",
    title: "DAGAN360 Live Race Management System",
    category: "CodeIgniter 4",
    desc: "Race checkpoint tracking system for managing runners, watchers, and live race progress in real time with monitoring and reporting tools.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/DAGAN360-Live-Race-Management-System",
    linkText: "View Project →",
  },
  {
    num: "16",
    title: "OJTrackPro Management System",
    category: "CodeIgniter 4",
    desc: "Web-based OJT tracking system for logging attendance, monitoring required hours, and tracking progress through reports and admin dashboards.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/OJTrackPro-Management-System",
    linkText: "View Project →",
  },
  {
    num: "17",
    title: "PWD Record Management System",
    category: "CodeIgniter 4",
    desc: "System that centralizes PWD profiles, services, appointments, payments, and reporting to improve record management and service delivery.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/PWD-Record-Management-System",
    linkText: "View Project →",
  },
  {
    num: "18",
    title: "Wedding Ring Management System",
    category: "CodeIgniter 4",
    desc: "Reservation system for managing ring inventory, customer reservations, payments, and administrative reporting with streamlined wedding planning workflows.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "CodeIgniter 4"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Wedding-Ring-Management-System",
    linkText: "View Project →",
  },
  {
    num: "19",
    title: "Gym Management System",
    category: "CodeIgniter 4",
    desc: "Web-based gym management platform for managing memberships, attendance, payments, class schedules, and general gym operations.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Gym-Management-System",
    linkText: "View Project →",
  },
  {
    num: "20",
    title: "Car Rental Management System",
    category: "CodeIgniter 4",
    desc: "Web-based car rental platform for vehicle browsing and reservations, including administrative tools for managing cars, customers, payments, and reports.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "CodeIgniter 4"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/Car-Rental-Management-System",
    linkText: "View Project →",
  },
];

export const TECHNICAL_CATEGORIES = [
  "ALL",
  "WEB DEVELOPMENT",
  "DATABASE",
  "PYTHON",
  "SYSTEMS",
  "QA / TESTING",
  "OTHER",
];
