export const PROJECTS = [
  {
    num: "01",
    title: "ResQR - Disaster Relief Management System",
    category: "Web Development",
    desc: "QR code-based disaster relief management system for registering beneficiaries, monitoring relief distribution, and coordinating emergency response operations.",
    tech: ["HTML", "CSS", "PHP", "MySQL"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/ResQR-Disaster-Relief-Management-System",
    linkText: "View Project →",
  },
  {
    num: "02",
    title: "RFID-Based CPSC Student Monitoring System",
    category: "Systems",
    desc: "RFID-based student monitoring system with automated photo capture, email notifications, Google Drive export, and administrative reporting.",
    tech: ["Python Django", "MySQL", "RFID", "Email Automation"],
    awards: ["Best Capstone Paper", "Best Capstone System"],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/RFID-Student-Monitoring-System",
    linkText: "View Project →",
  },
  {
    num: "03",
    title: "iTrak - Terminal Management System",
    category: "Systems",
    desc: "RFID-based terminal management system for monitoring driver attendance, managing routes and queues, processing payments, and providing real-time operational analytics.",
    tech: ["PHP", "MySQL", "HTML", "CSS"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/iTrak-Terminal-Management-System",
    linkText: "View Project →",
  },
  {
    num: "04",
    title: "DocuTrack - Document Tracking System",
    category: "Web Development",
    desc: "Document tracking system for organizing, archiving, tagging, and approving official letters, with Google Drive integration for centralized storage and synchronization.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "Google Drive API"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Document-Tracking-System-DocuTrack",
    linkText: "View Project →",
  },
  {
    num: "05",
    title: "Boarding House Rental System",
    category: "Web Development",
    desc: "Web-based boarding house rental platform for managing property listings, bookings, payments, and reviews with separate access for students, landlords, and administrators.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/BH-Rental-System",
    linkText: "View Project →",
  },
  {
    num: "06",
    title: "QR Attendance System",
    category: "Systems",
    desc: "QR code-based attendance tracking system for fast and contactless student monitoring during class entry and exit.",
    tech: ["Python", "OpenCV", "SQLite"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/qr-attendance-system",
    linkText: "View Project →",
  },
  {
    num: "07",
    title: "Payroll Compliance Tracker",
    category: "Database",
    desc: "Database-driven payroll compliance tracker for monitoring deductions, contributions, and regulatory requirements for local government units.",
    tech: ["PHP", "MySQL", "Bootstrap"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/payroll-compliance-tracker",
    linkText: "View Project →",
  },
  {
    num: "08",
    title: "Fleet Monitoring Dashboard",
    category: "Web Development",
    desc: "Fleet monitoring dashboard for tracking vehicle assignments, maintenance schedules, and operational status in real time.",
    tech: ["PHP", "MySQL", "Chart.js", "Bootstrap"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/fleet-monitoring-dashboard",
    linkText: "View Project →",
  },
  {
    num: "09",
    title: "Incident Report Logger",
    category: "Web Development",
    desc: "Incident reporting and logging system with role-based access, attachment support, and audit trail for operational incidents.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/incident-report-logger",
    linkText: "View Project →",
  },
  {
    num: "10",
    title: "Resident Record Manager",
    category: "Database",
    desc: "Resident record management system for barangay-level household profiling, document issuance, and reporting.",
    tech: ["PHP", "MySQL", "Bootstrap"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/resident-record-manager",
    linkText: "View Project →",
  },
  {
    num: "11",
    title: "Automated Email Notifier",
    category: "Python",
    desc: "Python automation tool for sending scheduled email notifications, reminders, and system alerts with templated content.",
    tech: ["Python", "SMTP", "Pandas"],
    awards: [],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/automated-email-notifier",
    linkText: "View Project →",
  },
  {
    num: "12",
    title: "Inventory Checker Bot",
    category: "Python",
    desc: "Automated inventory checker that scans stock records, flags low inventory, and generates summary reports.",
    tech: ["Python", "OpenPyXL", "SQLite"],
    awards: [],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/inventory-checker-bot",
    linkText: "View Project →",
  },
  {
    num: "13",
    title: "User Access Audit Tool",
    category: "QA / Testing",
    desc: "QA utility for auditing user access levels, permission inconsistencies, and role assignments across systems.",
    tech: ["Python", "MySQL", "Pandas"],
    awards: [],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/user-access-audit-tool",
    linkText: "View Project →",
  },
  {
    num: "14",
    title: "Form Validation Library",
    category: "Web Development",
    desc: "Reusable frontend form validation library with regex-based rules, error summaries, and accessibility-friendly markup.",
    tech: ["JavaScript", "HTML", "CSS"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/form-validation-library",
    linkText: "View Project →",
  },
  {
    num: "15",
    title: "API Response Tester",
    category: "QA / Testing",
    desc: "Lightweight API testing tool for validating endpoints, response times, status codes, and JSON schemas.",
    tech: ["Python", "Requests", "Pytest"],
    awards: [],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/api-response-tester",
    linkText: "View Project →",
  },
  {
    num: "16",
    title: "Database Seeder Utility",
    category: "Database",
    desc: "Database seeding utility for generating test records, resetting development schemas, and populating lookup tables.",
    tech: ["PHP", "MySQL", "Faker"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/database-seeder-utility",
    linkText: "View Project →",
  },
  {
    num: "17",
    title: "Session Hardening Module",
    category: "Web Development",
    desc: "Session security module implementing timeout policies, regeneration, IP binding, and brute-force mitigation.",
    tech: ["PHP", "Session Management", "Security"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/session-hardening-module",
    linkText: "View Project →",
  },
  {
    num: "18",
    title: "Batch Report Generator",
    category: "Database",
    desc: "Batch report generator that exports filtered database records into formatted spreadsheet and PDF reports.",
    tech: ["PHP", "MySQL", "PhpSpreadsheet", "PDF"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/batch-report-generator",
    linkText: "View Project →",
  },
  {
    num: "19",
    title: "Route Optimizer Prototype",
    category: "Systems",
    desc: "Route optimization prototype for terminal operations, reducing backtracking and improving queue throughput.",
    tech: ["Python", "NetworkX", "Pandas"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/route-optimizer-prototype",
    linkText: "View Project →",
  },
  {
    num: "20",
    title: "Bug Tracking Spreadsheet",
    category: "QA / Testing",
    desc: "Structured bug tracking spreadsheet with prioritization, status tracking, and weekly summary views for QA workflows.",
    tech: ["Excel", "Google Sheets", "QA Process"],
    awards: [],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/bug-tracking-spreadsheet",
    linkText: "View Project →",
  },
  {
    num: "21",
    title: "Local Payment Tracker",
    category: "Database",
    desc: "Local payment tracker for small-business transactions, daily reconciliation, and receipt logging.",
    tech: ["PHP", "MySQL", "Bootstrap"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/local-payment-tracker",
    linkText: "View Project →",
  },
  {
    num: "22",
    title: "Virtual Assistant Workflow Templates",
    category: "Digital",
    desc: "Digital workflow templates and automation assets created for virtual assistance, client onboarding, and social media operations.",
    tech: ["Notion", "Google Workspace", "Automation"],
    awards: [],
    image: "/images/experience/va/1.jpg",
    link: "https://github.com/chardoxx-3/va-workflow-templates",
    linkText: "View Project →",
  },
  {
    num: "23",
    title: "Social Media Content Calendar",
    category: "Digital",
    desc: "Content calendar and asset pack for consistent social media scheduling, caption drafting, and performance tracking.",
    tech: ["Google Sheets", "Canva", "Social Media"],
    awards: [],
    image: "/images/experience/techtuesday/1.jpg",
    link: "https://github.com/chardoxx-3/social-media-calendar",
    linkText: "View Project →",
  },
  {
    num: "24",
    title: "AI Chatbot Prompt Pack",
    category: "Digital",
    desc: "Curated prompt templates and workflow guides for AI-assisted customer support, research, and content creation.",
    tech: ["AI Prompting", "Workflow Design", "Copywriting"],
    awards: [],
    image: "/images/experience/aideas/1.jpg",
    link: "https://github.com/chardoxx-3/ai-chatbot-prompt-pack",
    linkText: "View Project →",
  },
  {
    num: "25",
    title: "Research Summary Templates",
    category: "Digital",
    desc: "Research summary templates and formatting guides for faster desk research, competitive analysis, and reporting.",
    tech: ["Notion", "Google Docs", "Research"],
    awards: [],
    image: "/images/experience/reverse/1.jpg",
    link: "https://github.com/chardoxx-3/research-summary-templates",
    linkText: "View Project →",
  },
  {
    num: "26",
    title: "Digital Operations Playbook",
    category: "Digital",
    desc: "Operations playbook covering task triage, client communication standards, file organization, and delivery checklists.",
    tech: ["Notion", "Process Design", "Documentation"],
    awards: [],
    image: "/images/experience/hackforgov/1.jpg",
    link: "https://github.com/chardoxx-3/digital-operations-playbook",
    linkText: "View Project →",
  },
];

export const TECHNICAL_CATEGORIES = [
  "ALL",
  "WEB DEVELOPMENT",
  "DATABASE",
  "PYTHON",
  "SYSTEMS",
  "QA / TESTING",
  "OTHER",
];

export const DIGITAL_CATEGORIES = [
  "ALL",
  "DIGITAL",
];
